version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mail_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    networks:
      - mailnet
    depends_on:
      - mailserver

  frontend:
    build: ./frontend
    container_name: mail_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - mailnet
    depends_on:
      - backend
  
  mysql:
    image: mysql:8.0
    container_name: mail_user_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tung12341
      MYSQL_DATABASE: mail_user
      MYSQL_USER: tamtanbk62
      MYSQL_PASSWORD: tung12341
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mailnet
  
  mailserver:
    build: ./mailserver
    container_name: custom_mailserver
    restart: unless-stopped
    hostname: yourdomain.com  
    ports:
      - "2525:25"   
      - "2143:143"  
      - "2587:587"  
      - "2993:993"
    volumes:
      - ./mail-data:/var/mail
      - ./mail-logs/mail.log:/var/log/mail.log
    networks:
      - mailnet


networks:
  mailnet:
    external: true